### ISSUE TITLE
how to set the value "geometricError" in tileset.json File

### ISSUE THREAD

**Issue by yanasdf789** [AnalyticalGraphicsInc/3d-tiles#137]
anybody can explain the geometricError?how to  calculate the value of " geometricError" in the following example 
https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Specs/Data/Cesium3DTiles/Tilesets/Tileset/tileset.json

**Comment by lilleyse** [comment]
Geometric error can be anything you want. At runtime geometric error is converted to screen-space error, which signifies how many pixels wrong the render would be if this tile was rendered but its children weren't. You can also think of it as the point where children become visible when zooming in. When a tile has a large geometric error it will refine to its children before a tile with a small geometric error.

In that example the geometric error values are made up. In more real-world example the geometric error may be calculated from the building height, volume, etc.

Feel free to ask questions like this on the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev), since github issues are for more for discussion of the spec.
