### ISSUE TITLE
the normal format in "b3dm" is different from that  in  KHR_binary_glTF

### ISSUE THREAD

**Issue by yanliasdf789** [AnalyticalGraphicsInc/3d-tiles#158]
I find that  the normal format in "[b3dm](url)" is different from that  in  "[KHR_binary_glTF](https://github.com/KhronosGroup/glTF/tree/master/specification/1.0)"!!!!!!
In  b3dm, the  componentType  is "byte ",the type is "VEC2";
int KHR_binary_glTF,the conponentType is "float",type is "VEC3";

anybody can explain the difference?

**Comment by lilleyse** [comment]
The b3dm you are looking is probably using oct-encoded normals, whereas the other model is using the more tradition float vec3. The b3dm format does not impose any rule on the normal format which is why you may find variations.

This post has some more details: https://cesiumjs.org/2016/08/08/Cesium-web3d-quantized-attributes/

> We already use two techniques for compressing normal and texture coordinate attributes in Cesium. Normal vectors are oct-encoded using the technique described in A Survey of Efficient Representations of Independent Unit Vectors, by Zina H. Cigolle, et al. This compresses three 32-bit floating-point numbers down to two bytes, a roughly 83% compression, so this approach is preferable to quantization of normals.
