### ISSUE TITLE
Very long URLs with multiple tilesetVersions appended

### ISSUE THREAD

**Issue by arneschilling** [AnalyticalGraphicsInc/3d-tiles#187]
Hi,

In the browser debugger I am seeing a lot of very long URLs when I include external models and shaders in my I3DM tileset.

Like this:

http://serverpathblabla.biz/datasource-data/appenzell_trees/proto_0.glb%20?v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456&v=1539250456

1539250456 is the tilesetVersion contained in each json file. If tilesetVersion is omitted, I am getting v=0.0 instead.

Currently my I3DM layer loads fine, but I am worried that in other network/server configurations this behavior might cause problems.

Test data set:
[appenzell_trees.zip](https://github.com/AnalyticalGraphicsInc/3d-tiles/files/820581/appenzell_trees.zip)
Location:
47.375308089093856N
9.42601203918457E

**Comment by lilleyse** [comment]
This problem should be fixed now in https://github.com/AnalyticalGraphicsInc/cesium/pull/5077.

I haven't tested with your tileset, since it is incompatible with the 3d-tiles head due to this fix: https://github.com/AnalyticalGraphicsInc/cesium/pull/5023. However I believe https://github.com/AnalyticalGraphicsInc/cesium/pull/5077 will solve this problem.

**Comment by pjcozzi** [comment]
@arneschilling thanks for the report as always, we just merged https://github.com/AnalyticalGraphicsInc/cesium/pull/5077.  Let us know if you run into anything.
