### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles#225]
From https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/222#issuecomment-303121639

>I definitely see the benefit of making padding rules part of the spec, not just an implementation note. I'll open a separate PR for that.

via @lilleyse

**Comment by lilleyse** [comment]
I believe these are all the padding requirements:

1. A tile's `byteLength` must be aligned to an 8-byte boundary.
2. The Feature Table binary (if present) must start and end on an 8-byte alignment
3. The Batch Table binary (if present) must start and end on an 8-byte alignment
4. The binary glTF (`b3dm` and `i3dm` only) (if present) must start and end on an 8-byte alignment
5. The `byteOffset` of Feature Table Binary property must be a multiple of the size of the property's `componentType`.
6. The `byteOffset` of a Batch Table binary property must be a multiple of the size of the property's `componentType`.
7. The Feature Table JSON must be padded with trailing Space chars (0x20) to satisfy alignment requirements of the Feature Table binary (if present)
8. The Batch Table JSON must be padded with trailing Space chars (0x20) to satisfy alignment requirements of the Batch Table binary (if present)
9. For `i3dm` if the `gltfFormat` is `0` (indicating the i3dm references an external gltf), the url must be padded to an 8-byte boundary in order to satisfy (1). This requires adding Space chars (0x20) to the end of the url, which must be removed at runtime.

Other notes/rationale:
* Number 1 is required so that tiles packed in a Composite tile have correct alignment
* Number 4 essentially reiterates 1/2/3. Tileset writers may need to edit `length` and the last `chunkData` accordingly in [glb](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#glb-file-format-specification)
* Number 2 and 3 are required since batch tables may include `DOUBLE` binary properties. The feature table doesn't yet have any `DOUBLE` properties, but it may in the future.
* Number 2 and 3 are following similar convention to glTF. Originally I had though of padding each binary property to 8-byte alignment but it's probably overkill.
* Every tile format (excluding `cmpt`) requires a Feature Table JSON, and therefore we can always add whitespace padding to JSON and guarantee that the binary/gltf sections will always start on an 8-byte alignment. This also means it's OK that tile headers are not 8-byte aligned (b3dm for example is 28-bytes) because there will always be padded JSON following the header.
* Number 9: see https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Instanced3DModel3DTileContent.js#L320-L328
* Number 9 is a bit confusing... what about storing the url in the feature table instead? Unfortunately this would be a breaking change to i3dm.

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301
