### ISSUE TITLE
Move CESIUM_RTC to the feature table for b3dm

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/3d-tiles#263]
Now that b3dm tiles have a feature table, it would probably make sense for  `RTC_CENTER` to exist in the feature table. It's still worth supporting `CESIUM_RTC` as a glTF extension, but the feature table `RTC_CENTER` seems preferable from a spec point of view.

**Comment by pjcozzi** [comment]
Would this eliminate the need for the `CESIUM_RTC` extension?  Can you draft up a quick schema example?

**Comment by lilleyse** [comment]
This is in scope for 1.0. It seems like less than one day of effort and should not affect backwards compatibility with the `CESIUM_RTC` extension.

This could also be a good item to add to the `upgrade` command in [3d-tiles-tools](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools).

**Comment by ggetz** [comment]
Resolved in https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/301

**Comment by caohaoze** [comment]
I think we should add Local_Geo_Center to b3dm, rather than RTC_CENTER, because the geo-position can be applied to different ellipsoid.
For example, if we don't use the WGS-1984 ellipsoid, the b3dm with RTC_CENTER may not be placed on the surface of the new ellipsoid accurately.
If we store the Local_Geo_Center with (lon, lat, height), we can use Cesium to calculate the matrix before rendering. This setting can make the data adapt to any kind of ellipsoid.

**Comment by lilleyse** [comment]
Hey @caohaoze, for now we are just trying to preserve the functionality of `CESIUM_RTC`. We may look into https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/286 for post-1.0 plans.

**Comment by lilleyse** [comment]
In response to using other ellipsoids at runtime - the tiles would be positioned correctly but wouldn't the tile contents not fit properly? Either there would be intersections at the edges for smaller ellipsoids or gaps for larger ellipsoids.
