### ISSUE TITLE
OGC Community Standard 

### ISSUE THREAD

**Issue by salutonalpha** [AnalyticalGraphicsInc/3d-tiles#294]
In the case that i3s has become an OGC community standard， whether 3D Tiles specification can become an OGC Community Standard ?

**Comment by pjcozzi** [comment]
@salutonalpha the OGC allows overlapping community standards, especially for emerging areas like 3D.  They have explicitly asked for 3D Tiles.

We just haven't finished the community standard process because we have had so much 3D Tiles interest, we have our hands full trying focusing on serving customers.  However, we will finish the community standard process soon.

**Comment by pjcozzi** [comment]
@salutonalpha we're going to finish the OGC Community Standard process very soon, hopefully to time everything with the next OGC TC meeting in June.  I'm going to close this issue to keep the GitHub issues tidy.  Thanks!
