### ISSUE TITLE
what's the coordinate system of gltf in 3d tiles?

### ISSUE THREAD

**Issue by wbz** [AnalyticalGraphicsInc/3d-tiles#318]
I tried  latitude，longitude，height in degrees and in radians，
and XYZ like 1214848.713735472，-4736533.690092559  4081508.242215981 。
but can't see the model on the earth。
can u give me some  examples?

**Comment by lilleyse** [comment]
glTF uses a Cartesian coordinate system were the y-axis is up. For more details check out the description in the `1.0` branch:

https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/specification#coordinate-reference-system-crs

The coordinates can be ECEF coordinates (1214848.713735472，-4736533.690092559, 
 4081508.242215981). However you will need to add a z-up-to-y-up transform as described in the implementation note in [this section](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/specification#order-of-transformations).

Note that ECEF coordinates will result in jittering issues at runtime due to precision problems. Instead it is better to define vertex data in local coordinates and use a [tile transform](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/specification#tile-transform) or [RTC_CENTER](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/1.0/specification/TileFormats/Batched3DModel#global-semantics) (not yet supported in Cesium, but will be soon).

**Comment by wbz** [comment]
3Q,i tried out and succeed already.

**Comment by learnerandtrainer** [comment]
Hi lilleyse, Do you have any idea about create  translated geometry using transform of local geometry coordinate system?
Before now I used pg2b3dm library  to create them but as you said jittering happened. I dont know how can translate my geometries . Can you show me the way?
