### ISSUE TITLE
 OSM model of New York 

### ISSUE THREAD

**Issue by wael3l** [AnalyticalGraphicsInc/3d-tiles#91]
is there any location from which we can download the OSM model of New York dataset , or its batched file and tileset file togther ? i wanted to work with 3d tile , and use the OSM model of New York  as my data source,however i could not find so far the b3dm file of NY and its tileset file online .

**Comment by Parthesh** [comment]
https://cesiumjs.org/NewYork/3DTiles/NewYork.zip

**Comment by wael3l** [comment]
Thanks !  but when i have opened the tileset , i guess its encoded by CRC32 ,and when i added its url as below, it did not work 
var tilesetUrl = '../../../Specs/Data/Cesium3DTiles/Tilesets/NewYork/';

is there a way to get it in jason format as normal tilesets ?

**Comment by pjcozzi** [comment]
> https://cesiumjs.org/NewYork/3DTiles/NewYork.zip

This is the right place to download the 3D Tiles tileset for the OSM NYC extract.  It is possible that it is out-of-date compared to Cesium's 3d-tiles branch.

@mramato if this is the case, can we update it?

**Comment by mramato** [comment]
That zip file is up to date, but all of the tiles are pre-gzipped and need to be served with `Content-Encoding` of `gzip` in order to be loaded by the browser.  How you set this header depends on what server technology you are using for the data.

We should probably include a README and simple node-based server with the zip to make serving tyhe data easy.  I'll keep this open and close it when that's done.

**Comment by pjcozzi** [comment]
> We should probably include a README and simple node-based server with the zip to make serving tyhe data easy. I'll keep this open and close it when that's done.

@mramato can you move this issue to another repo - even the Cesium 3d-tiles roadmap issue, https://github.com/AnalyticalGraphicsInc/cesium/issues/3241 - so we can keep this repo focused on spec issues?
